spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.chwordmqsrvakuarbdlo
    password: 6BYI12CSJLuO0bIo
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: "[%d-{HH:mm:ss.SSS}][%-5level][$logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
jwt:
  secret: DadFufN4Oui8Bfv3ScFj6R9fyJ9hD45E6AGFsXgFsRhT4YSdSb12
