spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        ddl-auto: validate
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace