spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.chwordmqsrvakuarbdlo
    password: ZSKxuQPBVOVSU4NU
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        ddl-auto: create
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug
auth:
  jwt:
    issuer: team.sprata.com
    secret: P04c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour : 3600000
